// Mocks generated by Mockito 5.4.6 from annotations
// in secret_notes/test/src/features/secret_notes/domain/usecases/delete_note_by_id_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:secret_notes/src/core/error/failures.dart' as _i5;
import 'package:secret_notes/src/features/secret_notes/domain/entities/note_entity.dart'
    as _i6;
import 'package:secret_notes/src/features/secret_notes/domain/repository/note_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i3.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>> createNote(
    _i6.NoteEntity? note,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [note]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>>.value(
                  _FakeEither_0<_i5.Failures, _i6.NoteEntity>(
                    this,
                    Invocation.method(#createNote, [note]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, List<_i6.NoteEntity>>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failures, List<_i6.NoteEntity>>
                >.value(
                  _FakeEither_0<_i5.Failures, List<_i6.NoteEntity>>(
                    this,
                    Invocation.method(#getAllNotes, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failures, List<_i6.NoteEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>> editNoteById(
    _i6.NoteEntity? note,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editNoteById, [note]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>>.value(
                  _FakeEither_0<_i5.Failures, _i6.NoteEntity>(
                    this,
                    Invocation.method(#editNoteById, [note]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failures, _i6.NoteEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, int>> deleteNoteById(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteById, [noteId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failures, int>>.value(
              _FakeEither_0<_i5.Failures, int>(
                this,
                Invocation.method(#deleteNoteById, [noteId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failures, int>>);
}
