// Mocks generated by Mockito 5.4.6 from annotations
// in secret_notes/test/src/features/secret_notes/presentation/cubit/update/edit_note_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:secret_notes/src/core/error/failures.dart' as _i6;
import 'package:secret_notes/src/features/secret_notes/domain/entities/note_entity.dart'
    as _i7;
import 'package:secret_notes/src/features/secret_notes/domain/repository/note_repository.dart'
    as _i2;
import 'package:secret_notes/src/features/secret_notes/domain/usecases/edit_note_by_id_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteRepository_0 extends _i1.SmartFake
    implements _i2.NoteRepository {
  _FakeNoteRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditNoteByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditNoteByIdUseCase extends _i1.Mock
    implements _i4.EditNoteByIdUseCase {
  MockEditNoteByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get noteRepository =>
      (super.noSuchMethod(
            Invocation.getter(#noteRepository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#noteRepository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, _i7.NoteEntity>> call(
    _i4.EditNoteParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failures, _i7.NoteEntity>>.value(
                  _FakeEither_1<_i6.Failures, _i7.NoteEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failures, _i7.NoteEntity>>);
}
