import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'injection.config.dart';
import 'package:objectbox/objectbox.dart';

/// All dependencies registered by Injectable will be resolved
/// through this instance.
final getIt = GetIt.instance;

/// Configures and initializes dependency injection for the application.
///
/// This function:
/// 1. Registers runtime dependencies that cannot be generated
///    automatically by Injectable (e.g., [Store]).
/// 2. Initializes all generated dependency registrations.
///
/// The [store] parameter must be provided at runtime because
/// it is created outside of the dependency injection system.
@InjectableInit(preferRelativeImports: true)
void configureDependencies({required Store store}) {
  // Registers ObjectBox Store as a singleton so it can be injected
  // into modules, repositories, and data sources.
  getIt.registerSingleton<Store>(store);

  // Initializes all dependencies generated by Injectable
  // (repositories, use cases, Cubits, modules, etc.).
  getIt.init();
}
