// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/secret_notes/data/models/note_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5989527492476513184),
    name: 'NoteModel',
    lastPropertyId: const obx_int.IdUid(5, 178500315144844026),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 635546430236687269),
        name: 'noteId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8422854790504071269),
        name: 'noteTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5478077929728940045),
        name: 'noteContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1567811807043980561),
        name: 'creationDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 178500315144844026),
        name: 'lastEditDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5989527492476513184),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteModel: obx_int.EntityDefinition<NoteModel>(
      model: _entities[0],
      toOneRelations: (NoteModel object) => [],
      toManyRelations: (NoteModel object) => {},
      getId: (NoteModel object) => object.noteId,
      setId: (NoteModel object, int id) {
        object.noteId = id;
      },
      objectToFB: (NoteModel object, fb.Builder fbb) {
        final noteTitleOffset = fbb.writeString(object.noteTitle);
        final noteContentOffset = fbb.writeString(object.noteContent);
        fbb.startTable(6);
        fbb.addInt64(0, object.noteId);
        fbb.addOffset(1, noteTitleOffset);
        fbb.addOffset(2, noteContentOffset);
        fbb.addInt64(3, object.creationDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.lastEditDate?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.noteId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastEditDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final noteIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final noteContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final creationDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final lastEditDateParam = lastEditDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastEditDateValue);
        final object = NoteModel(
          noteId: noteIdParam,
          noteTitle: noteTitleParam,
          noteContent: noteContentParam,
          creationDate: creationDateParam,
          lastEditDate: lastEditDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteModel] entity fields to define ObjectBox queries.
class NoteModel_ {
  /// See [NoteModel.noteId].
  static final noteId = obx.QueryIntegerProperty<NoteModel>(
    _entities[0].properties[0],
  );

  /// See [NoteModel.noteTitle].
  static final noteTitle = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[1],
  );

  /// See [NoteModel.noteContent].
  static final noteContent = obx.QueryStringProperty<NoteModel>(
    _entities[0].properties[2],
  );

  /// See [NoteModel.creationDate].
  static final creationDate = obx.QueryDateProperty<NoteModel>(
    _entities[0].properties[3],
  );

  /// See [NoteModel.lastEditDate].
  static final lastEditDate = obx.QueryDateProperty<NoteModel>(
    _entities[0].properties[4],
  );
}
